### ISSUE TITLE
Explore Firebase Analytics to meet David's CSV export needs

### ISSUE THREAD

**Issue by emaela** [sandboxnu/flow-in-the-field#118]
From David:
> RE: data collection, ideally we could pull the aggregated data in fixed intervals after deployment. It wouldn't need to be very often... could be weekly. It *definitely* doesn't need to be rapid. However, I also don't want to pull the data only after completion of the test because some people won't take the test, and we still want their other data. 
> 
> For the CSV, longer is better. So, ideally, each row would correspond to a specific trial for a specific person. For most of our analyses we end up wanting to transform anything in "wide" format into "long" format, so the longer it can be to start with the better. If each row gave us a subject ID, trial number, data/time, and all the relevant outcomes (e.g., response, accuracy, condition, response time) that would be ideal.

Needs summarized:
- Weekly CSV download
- Rows of CSV are rounds
- Attributes of each row are: user ID,  game type, number of words, session ID, round ID, round number, start time, end time, duration, score

Question to answer: Can we meet these need using Firebase Analytics? If so, what set-up is necessary?

**Comment by nicolesorial** [comment]
Here are the results: https://www.notion.so/sandboxnu/Analytics-SPIKE-results-118-f1f7e68a7fbf4b0c92ed694a1ae88b3d
