### ISSUE TITLE
Implement tutorial for the pairing game

### ISSUE THREAD

**Issue by emaela** [sandboxnu/flow-in-the-field#120]
We would like to display a game tutorial for the pairing game the first time a participant plays a session.

![Screen Shot 2022-02-14 at 6 12 15 PM](https://user-images.githubusercontent.com/25839028/153962485-8b916cdb-b854-41e0-a4a8-5a35b5646d66.png)

The tutorial will be on a bottom sheet modal with static cards that the participant can look through, as shown [on Figma](https://www.figma.com/file/VF38OjNZyeKzf1pEenoyXu/Wirerframes-(Copy)?node-id=518%3A402).
Note: on Figma there were two designs drafted, but the one that we have chosen to implement is the one pictured above.

We will later implement a help button to revisit the tutorial, but that has not been designed yet. We can treat that as a separate, later issue for now, unless it is designed before this issue is closed.

Specs:
- [ ] The tutorial bottom sheet modal is automatically shown when a participant starts their first pairing session.
- [ ] Each tutorial card is present in the carousel and the participant can swipe back and forth between them
- [ ] Clicking 'start session' on the last card, ends the tutorial and starts the game.
- [ ] Clicking the X, closes the tutorial and starts the game. 
- [ ] The tutorial is not automatically shown for pairing sessions after the participant's first session

**Comment by shashjar** [comment]
Closed with pr #137
