### ISSUE TITLE
Tutorial overlay looks incorrect

### ISSUE THREAD

**Issue by Octillerysnacker** [sandboxnu/flow-in-the-field#172]
How it should look according to figma:
<img width="415" alt="Screen Shot 2022-04-20 at 7 37 31 PM" src="https://user-images.githubusercontent.com/7697688/164343406-17517073-1412-4c14-bbb4-01b07410750d.png">

How it looks on Android:
<img width="415" alt="Screen Shot 2022-04-20 at 7 37 31 PM" src="https://user-images.githubusercontent.com/7697688/164343366-1c470f09-2825-4c57-a194-7a77e32680f8.jpg">

How it looks on iOS:
<img width="415" alt="Screen Shot 2022-04-20 at 7 37 31 PM" src="https://user-images.githubusercontent.com/7697688/164343408-281b8629-f093-414f-b9bd-0e98974cf49b.png">

**Comment by emaela** [comment]
I believe the difference here is what we want is a low opacity layer over the game screen (which would affect the color of all components underneath it), but currently we are just changing the background color of the game instead.
