### ISSUE TITLE
Start and end a session when player enters and exits game screen

### ISSUE THREAD

**Issue by emaela** [sandboxnu/flow-in-the-field#66]
Entering the game screen should trigger a new session to be created, and exiting the game screen should trigger the current session to end.

Specs:
In the Firebase interactor create a...
- [ ] field that keeps track of the current user
- [ ] field that keeps track of the current session
- [ ] method that creates a new session with the user's id and a start timestamp, and adds the session to the user's list of sessions
- [ ] method that ends the current session with an end timestamp

For the entering and exiting the game screen:
- [ ] When a user enters the game screen, a new session should be created in the Firestore and it should become the current session
- [ ] When a user exits the game screen, the current session should end (be given an end timestamp)
- [ ] When a user exits the game screen, there should no longer be a current session

[Backend brainstorm](https://www.notion.so/sandboxnu/Backend-Brainstorm-ea6267c98ce64b79b286733c1901261e) for reference on schemas.

**Comment by nicolesorial** [comment]
Manually testing, ran into the following:

For pairing: (tested with 2, 4, 8 pairs)
- Sessions are tracked in their collection, but not added to the `sessions` under the user collection
- Same thing for seen pairs

- Users assigned to selecting are still getting pairing -- couldn't test selecting
