### ISSUE TITLE
Email verification screen is cut off for small screens

### ISSUE THREAD

**Issue by emaela** [sandboxnu/flow-in-the-field#97]
Let's make the email verification screen responsive  so that it also works for small screens. Below is an image of how it currently looks for small screens, versus how [it was intended to look](https://github.com/sandboxnu/flow-in-the-field/pull/91):
![IMG_B95DF8A28781-1](https://user-images.githubusercontent.com/25839028/151710602-7d284d97-6e76-42ea-bdb4-aca72a765e21.jpeg)

**Comment by ShashJar** [comment]
Closed with PR #107
